### ISSUE TITLE
1.2.0: System.ArgumentOutOfRange error when loading any save file (Windows 7)

### ISSUE THREAD

**Issue by JayH2971** [functionFox/NaviDoctorLC#1]
Hello, a big thanks to you for making this utility. I'm hoping it'll help me enable Hard Mode on BN2, but we'll see how that works out.

When I open any BN1 or BN2 save file, I get an error window, as shown below. I blurred out my steam ID, which is the number being shown there. I'm not sure to what extent it'll affect my saves if I load them back in, but my Steam ID inside the editor resolves to 0 after loading.

All other data related to chips and HP seems to resolve correctly.

![image](https://github.com/functionFox/NaviDoctorLC/assets/37541932/c3809c2c-3da3-4640-9251-e52dec3501d6)

**Comment by Dillonzer** [comment]
@JayH2971 how many digits are your SteamID?

**Comment by JayH2971** [comment]
Actually, I'm probably getting something confused. The number in question is 9 digits, not 17 like a Steam ID would be.

**Comment by Dillonzer** [comment]
Alright thanks - I believe I now have this fixed on our dev branch. I'll see if we can get a patch out for this.

**Comment by Dillonzer** [comment]
Closing as this is fixed in https://github.com/functionFox/NaviDoctorLC/releases/tag/v1.2.0.1

**Comment by JayH2971** [comment]
Just tested the new release, and it loads my Steam ID and shows no error. Thank you!
