### ISSUE TITLE
1.2.0.1: Inaccuracies in loading BN2 save.

### ISSUE THREAD

**Issue by evarice8019** [functionFox/NaviDoctorLC#2]
Hi, when loading a BN2 save, the quantities in the app seem incorrect. In the screenshot, `BlkBomb` and `FtrSword` were legitimately obtained , but the app shows 2 `BlkBomb` of every code and 0 `FtrSword` of any code. I've changed the Steam ID in the screenshot to 0, so that is unrelated to this issue.

Platform: Steam(Windows 10)

![image](https://github.com/functionFox/NaviDoctorLC/assets/35512190/010fac5d-3612-4e8d-89ca-d823a15bf094)

**Comment by functionFox** [comment]
Thank you for pointing this out, I'll look into this right away.

**Comment by functionFox** [comment]
There was a problem in how the Secret Chips section was read, but the write function operates as intended. This has been fixed and a new revision will be available shortly.

**Comment by functionFox** [comment]
The fix is now available: https://github.com/functionFox/NaviDoctorLC/releases/tag/v1.2.0.2
